// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_class_msde_hestModel();
RcppExport SEXP _rcpp_module_boot_class_msde_lotvolModel();
RcppExport SEXP _rcpp_module_boot_class_msde_biouModel();
RcppExport SEXP _rcpp_module_boot_class_msde_pgnetModel();
RcppExport SEXP _rcpp_module_boot_class_msde_eouModel();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_class_msde_hestModel", (DL_FUNC) &_rcpp_module_boot_class_msde_hestModel, 0},
    {"_rcpp_module_boot_class_msde_lotvolModel", (DL_FUNC) &_rcpp_module_boot_class_msde_lotvolModel, 0},
    {"_rcpp_module_boot_class_msde_biouModel", (DL_FUNC) &_rcpp_module_boot_class_msde_biouModel, 0},
    {"_rcpp_module_boot_class_msde_pgnetModel", (DL_FUNC) &_rcpp_module_boot_class_msde_pgnetModel, 0},
    {"_rcpp_module_boot_class_msde_eouModel", (DL_FUNC) &_rcpp_module_boot_class_msde_eouModel, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_msde(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
